---
githubRepo: https://github.com/aviarytech/tev2-test.wiki.git
# TEv2 Curated Text Header
term: curated-text
termType: concept
isa:
glossaryText: a text that documents a [concept](@) or other [knowledge artifact](@) of a specific [community](@) or other [party](@), and is located within a [scope](@) that is owned by that [community](@)/[party](@).
synonymOf:
groupTags:
formPhrases: curated-text{ss}, ctext{ss}
# Curation status
status: proposed
created: 2023-10-31
updated: 2023-10-31
# Origins/Acknowledgements
contributors: BrianR
attribution: "[Aviary Tech](https://aviary.tech)"
originalLicense: "[CC BY-SA 4.0](http://creativecommons.org/licenses/by-sa/4.0/?ref=chooser-v1)"
