name: Test TEv2 Workflow

on:
  gollum:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    name: Run TEv2
    runs-on: ubuntu-latest

    steps:
    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Install dependencies
      run: bun install
      
    - name: Run @aviarytech/tev2-ingress
      run: bun tev2-ingress -c config.yaml
            
    # - name: Run @tno-terminology-design/mrg-import
    #   run: bun mrg-import -s .
      
    - name: Run @tno-terminology-design/mrgt
      run: bun mrgt -s .
      
    - name: Run @aviarytech/tev2-hrgt
      run: bun tev2-hrgt glossaries/mrg* 
      
    - run: mkdir deploy && mv index.html deploy
    
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./deploy
