name: Test TEv2 Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test-tev2:
    runs-on: ubuntu-latest

    steps:
    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
            
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: bun add @aviarytech/ingress @aviarytech/hrgt @tno-terminology-design/mrg-import

    - name: Run @aviarytech/ingress
      run: bun run @aviarytech/ingress

    - name: Run @tno-terminology-design/mrg-import
      run: bun run @tno-terminology-design/mrg-import

    - name: Run @aviarytech/hrgt
      run: bun run @aviarytech/hrgt
